Ft/tools page
EnAccess/co-design-FE pull request #18
Opened 2024-03-19 09:50 UTC by AdelineA

- Add basic tools component
- Add technical approach component
- Add a multidisciplinary approach component
- Add participatory approach component
- Add a human design approach
- Add behaviour approach
- Add title card

2024-03-21 08:50 UTC, kareraolivier reviewed
Hello @AdelineA  good work , 
I have left some few suggestion you can look at them

2024-03-21 08:50 UTC, kareraolivier commented on src/components/toolscomponents/TechnicalApproach.tsx
> +          className=""
It would help if you add all yellow card in outside file

2024-03-21 08:50 UTC, kareraolivier commented on src/components/toolscomponents/arrows/HorizontalArrows.tsx
> +      <div className="-rotate-[132deg] pt-20">
configure degree in tailwind.config

2024-03-21 08:50 UTC, kareraolivier commented on src/components/toolscomponents/behavior/BehaviorByPractice.tsx
> +  approachEntries: Entry[];
every where you use `Entry[]` can be replaced by `Entries` It is created

2024-03-21 08:50 UTC, kareraolivier commented on src/components/toolscomponents/behavior/BehaviorByTheory.tsx
> +}
here also

2024-03-21 08:50 UTC, kareraolivier commented on src/components/toolscomponents/humanDesign/HumanDesignByTheoryApproach.tsx
> +  approachEntries: Entry[];
check all of you interfaces

2024-03-22 07:51 UTC, kareraolivier approved these changes
Good work

2024-03-22 15:32 UTC, NNesta requested changes

2024-03-22 15:32 UTC, NNesta commented on src/pages/tools-resources.tsx
> +  );
Can you create the index file inside each section folder where you can put all of those subsections instead of putting them together here.

2024-03-22 15:32 UTC, NNesta commented on src/components/icons/SmallArrow.tsx
> +          fill-rule="evenodd"
change this fill-rule to fillRule to avoid Invalid DOM property warning

2024-03-22 15:32 UTC, NNesta commented on src/components/toolscomponents/behavior/BehaviorByPractice.tsx
> +import { Entries } from "../../../types/interfaces";
I think here and other sections in this page you can create inside the folder the Practice and Theory subsections in its own files and  their components and then create an index file and put a component like Behavior where you will put together all subsections and their title to make an entire section.

2024-04-12 18:04 UTC, closed without merging