feat: add footer component
EnAccess/co-design-FE pull request #30
Opened 2024-04-18 06:56 UTC by AdelineA

- add footer component

2024-04-18 09:05 UTC, NNesta requested changes

2024-04-18 09:05 UTC, NNesta commented on src/components/footer/data-source.ts
> +export const uniqueDataSources = Array.from(new Set(dataSources));
Can you change this name of this variable to name that give hint what it hold

2024-04-18 09:05 UTC, NNesta commented on src/components/footer/index.tsx
> +          >
Can you align the content to the right side as on the design

2024-04-22 16:48 UTC, NNesta approved these changes
LGTM

2024-04-24 08:30 UTC, musayann requested changes

2024-04-24 08:30 UTC, musayann commented on src/components/footer/data-resources.ts
> +const dataResources = output
these should be in the `src/data` folder

2024-04-24 12:33 UTC, NNesta requested changes

2024-04-24 12:33 UTC, NNesta commented on src/data/footer/index.tsx
> +const Footer = () => {
Can you put this component inside components folder

2024-04-24 13:51 UTC, NNesta approved these changes
LGTM

2024-04-25 14:06 UTC, musayann approved these changes

2024-04-25 14:06 UTC, merged