feat: add zotero json output support
EnAccess/co-design-FE pull request #42
Opened 2024-06-12 11:47 UTC by musayann

2024-06-12 12:25 UTC, NNesta requested changes

2024-06-12 12:25 UTC, NNesta commented on src/components/cards/Node.tsx
> +            <p className="z-10">{data.authors}</p>
Can you do conditional rendering for both data.title and data.authors

2024-06-12 12:25 UTC, NNesta commented on src/components/cards/Node.tsx
>                </p>
Can you also add condition rendering for data.title and data.authors

2024-06-12 13:32 UTC, kareraolivier reviewed
We are also not using `generate-output-json.js`

2024-06-12 13:32 UTC, kareraolivier commented on src/data/case-studies/index.ts
> +import output from "@/data/zotero";
This block of code here 
```jsx 
const toolKits = output.filter(
  (data) => data?.PARSED_MANUAL_TAGS["CORE_TOOLKIT"]
);
```
Is updated to: 
```jsx
const toolKits = output.filter(
  (data) => data?.PARSED_MANUAL_TAGS["CORE TOOLKIT"]
);
```

2024-06-13 09:27 UTC, musayann commented on src/data/data-resources.ts
> +  "Open Source",
why are we hardcoding these values ?

2024-06-13 10:34 UTC, merged